### ISSUE TITLE
The image links for nightly builds is broken (error 403)

### ISSUE THREAD

**Issue by Firefighter1023** [mkevenaar/FarmPi#28]
#### FarmPi version

Version: Nightly

What were you doing?

Attempting to download the nightly image from the farmpi GitHub.

Access the farmpi GitHub, follow the links to the nightly building, attempt to download the latest image, receive an error 403 access denied.

What did you expect to happen

I expected the precompiled image to download.

What happened instead?

No download occurred, received access denied error.

**Comment by mkevenaar** [comment]
This seems to be solved now. Can you verify?
