### ISSUE TITLE
Nightly builds should have their own version number

### ISSUE THREAD

**Issue by mkevenaar** [mkevenaar/FarmPi#8]
The FarmPi image currently shows the same version number as the final build will be, the scheduled build should add some date/time after the version number (e.g. 0.1.0-20210622) to show that this is a nightly build image.

**Comment by davidzwa** [comment]
Interested in knowing how to do this as well: @octofarm/client NPM package and OctoFarm Companion plugin require a build number as well.

**Comment by mkevenaar** [comment]
Fixed here: be79b9e
